Added Go embed demo (Go 1.16)
EngoEngine/engo pull request #759
Opened 2021-02-17 10:33 UTC by raziel2244

Added another demo to show how to embed using Go embed.

Does require go.mod to be set to Go 1.16 so this should probably be held back for a while.

2021-02-17 10:39 UTC, raziel2244 commented
Ah yeah forgot those would need updating, updating those now.

2021-02-17 11:01 UTC, raziel2244 commented
Okay so still not passing... think I'll just keep this aside for later. Once 1.16 is more established and Engo maybe gets a go.mod update for some reason besides this it can be looked into again.

For anyone looking to embed using Go embed, examples can be provided elsewhere worst case.

2021-02-17 11:07 UTC, raziel2244 commented
Reopened as WIP to keep it tracked here for the future.

2021-02-17 21:48 UTC, Noofbiz commented
I fixed the traffic manager issues, so they should pass if they re-run. The only issue I see is I think engo's go mod version should stay 1.14. Even though 1.16 is required for the embedding, that's not a feature engo itself uses so it shouldn't need to increase the version for it.

2021-02-17 22:02 UTC, Noofbiz requested changes

2021-02-17 22:02 UTC, Noofbiz commented on go.mod
> +go 1.16
This shouldn't need to be updated, only testing

2021-02-17 22:04 UTC, raziel2244 commented
Thanks, yeah I was thinking it's probably best to leave the go version for Engo as 1.14. Unfortunately, since the demo is within the module it fails to build without the update to go.mod.

2021-02-17 22:17 UTC, raziel2244 commented
Just looking to see if there is a way to set the -lang flag for build as that could be a way round it, maybe.

2021-02-17 22:30 UTC, raziel2244 commented
Can't see a way around it for now, unfortunately. The demo can live elsewhere in the meantime though, such as just in the README file.

2021-03-18 19:02 UTC, Noofbiz commented
Alright, got the CI stuff working. Turns out the go.mod includes the demos, but it's not a hard/fast rule. I think 1.16 is mature enough at this point to move up to it if you want to merge this in. Looks good to me!

2021-03-18 19:02 UTC, Noofbiz approved these changes

2021-03-18 19:24 UTC, eth0net commented
Ah well if you're happy to up the Go version then go ahead with the merge, I believe this is all ready!

2021-03-18 19:34 UTC, merged